### ISSUE TITLE
Qt 5.x compiling issue

### ISSUE THREAD

**Issue by xavier7179** [lunarcloud/qt-enhanced-project-template#10]
I tried both Qt 5.5.1 and Qt 5.4.2 and I stil got this error:

- error: no type named 'setApplicationIconBadgeNumber' in namespace 'QtMac'
    QtMac::setApplicationIconBadgeNumber(number);

According to Qt Creator auto-completion is not available.

**Comment by lunarcloud** [comment]
http://doc.qt.io/qt-5/qtmac.html#setApplicationIconBadgeNumber
It exists, so it may be an issue with the include? I don't own an Apple computer anymore, so I can't personally investigate.

**Comment by jakepetroules** [comment]
setApplicationIconBadgeNumber is only available on iOS. The OS X equivalent is setBadgeLabelText. I've fixed it.
